# use the alpine base image
FROM alpine:3.3
MAINTAINER Daniël van Gils

RUN mkdir -p /app
WORKDIR /app

# copy the binary
COPY ./artifacts/compiled/starter /app
COPY ./templates /app/templates
CMD /app/starter -daemon -templates templates
