source 'https://rubygems.org'
ruby '2.2.2'

gem 'rails', '4.2.2'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'jbuilder', '~> 2.0'
gem 'bootstrap-sass'
gem 'font-awesome-sass', '~> 4.3.0'
gem 'devise'
gem 'devise-i18n'
gem 'devise_invitable'
gem 'omniauth-facebook'
gem 'koala'
gem 'haml-rails'
gem 'high_voltage'
gem 'mysql2'
gem 'pundit'
gem 'simple_form'
gem 'unicorn'
gem 'unicorn-rails'
gem 'summernote-rails'
gem 'sentient_user'
gem 'paper_trail'
gem 'rolify'
gem 'friendly_id'
gem 'momentjs-rails'
gem 'public_activity'
gem 'crummy'
gem 'refile', require: 'refile/rails'
gem 'refile-mini_magick'
gem 'impressionist'
gem 'dotenv-rails'
gem 'globalize', '~> 5.0.0'
gem 'globalize-versioning', '~> 0.1.0'
gem 'route_translator'
gem 'lograge'
gem 'peek', github: 'eitoball/peek', branch: 'update-gems'
gem 'peek-git'
gem 'peek-performance_bar'
gem 'peek-mysql2'
gem 'peek-gc'
gem 'peek-rblineprof'
gem 'pygments.rb', require: false
gem 'intercom-rails'

group :development do
  gem 'better_errors'
  gem 'foreman'
  gem 'guard-bundler'
  gem 'guard-rails'
  gem 'guard-rspec'
  gem 'guard-livereload', '~> 2.4', require: false
  gem 'html2haml'
  gem 'hub', require: nil
  gem 'quiet_assets'
  gem 'rails_layout'
  gem 'rb-fchange', require: false
  gem 'rb-fsevent', require: false
  gem 'rb-inotify', require: false
  gem 'spring-commands-rspec'
  gem 'pry-remote'
  gem 'xray-rails'
end

group :development, :test do
  gem 'factory_girl_rails'
  gem 'faker'
  gem 'pry-rails'
  gem 'pry-rescue'
  gem 'rspec-rails'
  gem 'rubocop'
  gem 'byebug'
  gem 'web-console', '~> 2.0'
  gem 'spring'
  gem 'i18n-tasks', '~> 0.8.3'
  gem 'bullet'
end

group :staging, :production do
  gem 'rails_12factor'
  gem 'sentry-raven', github: 'getsentry/raven-ruby'
end

group :test do
  gem 'capybara'
  gem 'database_cleaner'
  gem 'launchy'
  gem 'poltergeist'
  gem 'fuubar'
  gem 'codeclimate-test-reporter', require: nil
  gem 'simplecov', require: false
  gem 'shoulda-matchers'
end
