source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.1'
# Use postgresql as the database for Active Record
gem 'pg'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.1.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby
gem 'uuidtools'
# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'honeybadger', '~> 2.0'
gem 'sidekiq'
gem 'sidekiq-failures'
gem 'seed_dump'
gem 'devise'
gem 'simple_token_authentication', '~> 1.0'
gem 'fuzzy_match'

gem 'activeadmin', github: 'activeadmin'
gem 'redis'
gem 'whenever', require: false
gem 'sinatra', require: nil

gem 'flattened_active_admin', '~> 0.0.3'

gem 'inherited_resources'
gem 'responders'

gem 'ragamuffins'
gem 'paginative'
gem 'notify_user', github: 'Papercloud/notify_user'
gem 'wolverine'

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

gem 'foreman'
# Use Unicorn as the app server
gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# Generate controllers and doc(k)s
gem 'harbourmaster'

# Truncate html without breaking things
gem 'truncate_html'

# Only send emails to the places that we want.
gem 'safety_mailer'

group :development, :test do
  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'

  gem 'rspec-rails', '~> 3.2.1'
  gem 'factory_girl_rails'
  gem 'awesome_print'
  gem 'pry'
  gem 'guard'
end

group :development do
  gem 'overcommit'
  gem 'better_errors'
  gem 'validation_rage'
  gem 'quiet_assets'
  gem 'binding_of_caller'
  gem 'annotate'
  gem 'guard-livereload', '~> 2.4', require: false
  gem 'restkit_generators', github: 'Papercloud/restkit_generators', branch: 'develop'
  gem 'letter_opener'
end

gem 'rubocop', require: false

group :test do
  gem 'database_cleaner'
  gem 'spring-commands-rspec'
  gem 'vcr'
  gem 'shoulda-matchers', require: false
  gem 'timecop'
  gem 'bullet'
  gem 'mock_redis'
  gem 'rspec-sidekiq'
end
